cargo-config: rename to config.toml
cargo recently complains about our cargo configuration file name:

    $ cargo build
    warning: `vhost/.cargo/config` is deprecated in favor of
    `config.toml`
    note: if you need to support cargo 1.38 or earlier, you can
    symlink `config` to `config.toml`

As suggested, let's update the file name. We don't create the symlink
since 2021 edition is not supported by 1.38 toolchain:

    $ cargo +1.38.0 build
    error: failed to parse manifest at ...

    Caused by:
      failed to parse the `edition` key

    Caused by:
      supported edition values are `2015` or `2018`, but `2021` is unknown

Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>