video: don't needlessly clone Waker
Clippy complains about Option::take() called on a temporary value:

```text
error: called `Option::take()` on a temporary value
   --> vhost-device-video/src/stream.rs:125:30
    |
125 |         if let Some(waker) = self.waker().take() {
    |                              ^^^^^^^^^^^^^^^^^^^
    |
    = note: `waker` creates a temporary value, so calling take() has no effect
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_option_take
    = note: `-D clippy::needless-option-take` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::needless_option_take)]`
```

But Waker is meant to be consumed when calling Waker::wake, so there's
no need to clone temporary values. Move the .wake() call inside
ResourceState's set_ready() method so we don't have to lock the mutex
again.

Signed-off-by: Manos Pitsidianakis <manos.pitsidianakis@linaro.org>