clippy: Fix clippy::dangling_pointers_from_temporaries
Fix `clippy::dangling_pointers_from_temporaries` reported by clippy
0.1.85 (4d91de4e48 2025-02-17). Use slice instead of vector.

```console
error: a dangling pointer will be produced because the temporary `std::vec::Vec<i32>` will be dropped
   --> vhost-device-spi/src/spi.rs:913:32
    |
913 |             tx_buf: vec![7, 4].as_ptr() as u64,
    |                     ---------- ^^^^^^ this pointer will immediately be invalid
    |                     |
    |                     this `std::vec::Vec<i32>` is deallocated at the end of the statement, bind it to a variable to extend its lifetime
```

Signed-off-by: Ruoqing He <heruoqing@iscas.ac.cn>