gpio: re-arrange start_backend to handle config errors
The compiler warns with the move that:

  error: variants `CouldNotOpenDevice`, `CouldNotCreateGpioController`, `CouldNotCreateBackend`, and `CouldNotCreateDaemon` are never constructed
    --> crates/vhost-device-gpio/src/backend.rs:43:5
     |
  31 | pub(crate) enum Error {
     |                 ----- variants in this enum
  ...
  43 |     CouldNotOpenDevice(crate::gpio::Error),
     |     ^^^^^^^^^^^^^^^^^^
  44 |     #[error("Could not create gpio controller: {0}")]
  45 |     CouldNotCreateGpioController(crate::gpio::Error),
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  46 |     #[error("Could not create gpio backend: {0}")]
  47 |     CouldNotCreateBackend(crate::vhu_gpio::Error),
     |     ^^^^^^^^^^^^^^^^^^^^^
  48 |     #[error("Could not create daemon: {0}")]
  49 |     CouldNotCreateDaemon(vhost_user_backend::Error),
     |     ^^^^^^^^^^^^^^^^^^^^
     |
     = note: `Error` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
     = note: `-D dead-code` implied by `-D warnings`

  error: could not compile `vhost-device-gpio` (bin "vhost-device-gpio") due to previous error

Because we never really care about failure within the spawn loop.
Handle this by ensuring errors propagate back to the caller.

Signed-off-by: Alex Bennée <alex.bennee@linaro.org>